version: "2"

services:
  raifa_bot:
    build: .
    container_name: RaiferBot
    image: raifer_bot
    command: >
      bash -c "python3 main.py
      && mkdir ./src/data
      && mkdir ./src/logs"
    ports:
      - 5000:5000
    volumes:
      - ./:/app/
      - /home/raifa_bot/data/:/app/src/data/
      - /tmp/raifa_bot/logs/:/app/src/logs/
    env_file:
      - .env
    restart: always